version: "3"
services:
    react-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:80"
        volumes:
            - /app/node_modules
            - .:/app
        environment:
            - REACT_APP_BACKEND_URL=http://localhost:5000
    
